function map = joystickmap()
    eventcodes = maze_events();
    
    map = [%1,  eventcodes.LL;...
           %3,  eventcodes.RL;...
           11, eventcodes.LL;...
           16, eventcodes.RL;...
           4,  eventcodes.TM;...
           2,  eventcodes.TMS;...
           5,  eventcodes.MV;...
           6,  eventcodes.MV;...
           9,  eventcodes.LV;...
           10, eventcodes.RV;...
           %11,  eventcodes.DECSPEED;...
           12,  eventcodes.INCSPEED;...
           17,  eventcodes.DECSPEED;...
           %16,  eventcodes.INCSPEED;...
           ];

end
